name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew android:assembleDebug
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
    - name: Upload Android artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Mindustry/android/build/outputs/apk/standard/release/Mindustry-BE-Android-${{ env.RELEASE_VERSION }}.apk
        tag: ${{ github.ref }}
