name: Pull Request Tests

on: [pull_request, workflow_dispatch]

jobs:
  buildJava14:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Give permision
      run: chmod +x ./gradlew
    - name: build JAR
      run: ./gradlew desktop:dist
    - name: Upload desktop JAR for testing
      uses: actions/upload-artifact@v2
      with:
        name: Desktop JAR (zipped)
        path: desktop/build/libs/Mindustry.jar
