name: Tests

on: [push, workflow_dispatch]

jobs:
  buildJava14:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Give permision
      run: chmod +x ./gradlew
    - name: Run unit tests
      run: ./gradlew clean cleanTest test
