name: Tests

on: [push, workflow_dispatch]

jobs:
  buildJava14:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Give permision
      run: chmod +x ./gradlew
    - name: Run unit tests
      run: ./gradlew clean cleanTest test
    - name: Trigger BE build
      if: ${{ github.repository == 'youngterror3/mindustry' }}
      run: |
        git clone --depth=1 --branch=main https://github.com/youngterror3/sidus-victor-builds ../sidus-victor-builds
        cd ../sidus-victor-builds
        BNUM=$(($GITHUB_RUN_NUMBER + 20000))
        git tag ${BNUM}
        git config --global user.name "Build Uploader"
        git push https://youngterror3:${{ secrets.API_TOKEN_GITHUB }}@github.com/youngterror3/sidus-victor-builds ${BNUM}
